POST http://localhost:8000/signup HTTP/1.1
Content-Type: application/json

{
	"fullName": "arnab",
	"email": "test312@test.com",
	"password": "test"
}

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
	"email": "test@test.com",
	"password": "test"
}

###

POST http://localhost:8000/add-product HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJ0ZXN0MTRAdGVzdC5jb20iLCJpYXQiOjE2MzE5NjQ1MjksImV4cCI6MTYzMTk2NDU4OX0.d4hTaEofkF1EEKwtoVxAsVSxSJja25LHsEJMWTRbRJU

{
	"productName": "bike",
	"productDescription": "This is a demo bike",
	"productPrice": 500,
	"userID": 14
}
###

GET http://localhost:8000/products?page=100&limit=5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJ0ZXN0MTRAdGVzdC5jb20iLCJpYXQiOjE2MzE4MjE2NzcsImV4cCI6MTYzMTgyMTY5Mn0.5Qe3BympV229bF83YT-RgZw9DQkB3JkQU5KCT2EqefA

###

PUT http://localhost:8000/update-product HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUz1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJ0ZXN0MjAxQHRlc3QuY29tIiwiaWF0IjoxNjMyMDYzNjk4LCJleHAiOjE2MzIwNjk2OTh9.RprTIrH3xi4dRwbyRTuET1oys0vmMfXV5etQxRVuvTs

{
	"productID": 1,
	"productName": "super bike2",
	"productDescription": "This is a demo bike",
	"productPrice": 500,
	"userID": 14
}

###

GET http://localhost:8000/search-product?productName=car HTTP/1.

###

DELETE http://localhost:8000/delete-product?productID=50 HTTP/1.
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNjMyMDY2NjM5LCJleHAiOjE2MzIwNzI2Mzl9.Itp0fELJuVK4sNQ9eCWSN-pTI7GyGIzgzmGLt2rEj4Q
###

GET http://localhost:8000/check-token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJ0ZXN0MTRAdGVzdC5jb20iLCJpYXQiOjE2MzE5NjQ1NzMsImV4cCI6MTYzMTk2NDYzM30.a7YutnKH_1a91UmyG_OzEfynP15NX92ht8AgPyC7jso